language: php

dist: bionic

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

install: travis_retry composer install

script: vendor/bin/phpunit
